---
- name: "install | add maas ppa repository"
  apt_repository:
    repo: "{{ maas.repository }}"
    state: "present"
    update_cache: true

- name: "install | ensure requirements are installed"
  package:
    name: "{{ maas_rackd.requirements }}"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "install | install maas-rack-controller"
  package:
    name: "{{ maas_rackd.package }}"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
